name: proyecto
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  flutter_hooks: ^0.19.0
  freezed_annotation: ^2.2.0
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  google_mlkit_text_recognition: ^0.15.0
  hooks_riverpod: <2.6.0
  image_picker: ^1.0.4
  lottie: ^2.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.2.1
  riverpod_annotation: <2.6.0
  shared_preferences: ^2.1.2
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.0
  riverpod_generator: <2.6.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#069494"

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/